[build]
  # This command runs your build script using the local Angular CLI
  command = "npm run build"
  # This must match exactly what is in your angular.json "outputPath"
  publish = "dist/urban-builtform-architects/browser"

[environment]
  # Force Netlify to use the stable version of Node
  NODE_VERSION = "20"